# Generated by Django 5.0 on 2025-08-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkcontent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='events/images/')),
                ('event_date', models.DateTimeField()),
                ('event_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
