# Generated by Django 5.0 on 2025-08-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('talkmarketplace', '0002_productmixin_polymorphic_ctype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductMixin',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='marketplaceproduct',
            old_name='productmixin_ptr',
            new_name='product_ptr',
        ),
        migrations.RenameField(
            model_name='takaproduct',
            old_name='productmixin_ptr',
            new_name='product_ptr',
        ),
        migrations.AddField(
            model_name='saveditem',
            name='product',
            field=models.ManyToManyField(related_name='saved_items', to='talkmarketplace.product'),
        ),
    ]
